sudo: required
dist: trusty
language: node_js
node_js: stable
services:
  - docker
branches:
  only:
  - master

cache:
  directories:
  - node_modules

stages:
  - name: unit testing
    if: type = pull_request
  - name: deploy to staging
    if: type = pull_request
  - name: deploy to production
    if: type = push

jobs:
  include:
    - stage: unit testing
      before_install:
      - export CHROME_BIN=chromium-browser
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start

      before_script:
      - npm install -g angular-cli
      - yarn

      script: ng test --single-run

    - stage: deploy to staging
      before_script:
      - npm install -g firebase-tools
      - npm install -g @angular/cli

      script:
      - ng build --prod --aot

      after_success:
      - firebase use staging
      - firebase deploy --token $FIREBASE_TOKEN

    - stage: deploy to production
      before_script:
      - npm install -g firebase-tools
      - npm install -g @angular/cli

      script:
      - ng build --prod --aot
      - mv Dockerfile ./dist/Dockerfile
      - cd dist
      - docker build -t my-angular-app .
      - docker run -p 80:80 -d my-angular-app

      after_success:
      - firebase use production
      - firebase deploy --token $FIREBASE_TOKEN
      - docker login -u atean -p WXg9@O*LB@0xG%6d
      - docker push atean/tdt4242-app
