sudo: required
dist: trusty
language: node_js
node_js: stable

branches:
  only:
  - master

cache:
  directories:
  - node_modules

services:
  - docker

stages:
  - name: unit testing
    if: (type = pull_request) AND (branch = master)
  - name: deploy to stage
    if: (type = push) AND (branch = master)

jobs:
  include:
    - stage: unit testing
      before_install:
      - export CHROME_BIN=chromium-browser
      - export DISPLAY=:99.0
      - sh -e /etc/init.d/xvfb start
      - sleep 3

      before_script:
      - npm install -g angular-cli
      - npm install

      script:
      - npm run build --aot
      - ng test --single-run

    - stage: deploy to stage
      before_script:
      - npm run build --aot
      - cd server
      - npm install
      - cd ..

      script:
      - docker build -t tdt4242-exercise2-group8-stage .
      - docker tag tdt4242-exercise2-group8-stage:latest registry.heroku.com/tdt4242-exercise2-group8-stage/web
      - docker login --username=_ --password=$HEROKU_AUTH_TOKEN registry.heroku.com
      - docker push registry.heroku.com/tdt4242-exercise2-group8-stage/web
